from .person_model import Person
from .education_model import Qualification
from .academic_year_model import AcademicYear
from .semester_model import Semester
from .experience_model import Experience
## User model import removed
from .faculty_model import Faculty
from .faculty_contract_model import FacultyContract
from .faculty_transfer_model import FacultyTransfer
from .faculty_course_history_model import FacultyCourseHistory
from .tracks_model import Track
from .faculty_track_assignment_model import FacultyTrackAssignment
from .campus_model import Campus
from .school_model import School
from .campus_school import CampusSchoolAssociation
from .department_model import Department
from .course_model import Course
from .program_model import Program
from .program_course import ProgramCourseAssociation
from .audit_model import Audit
from .track_level import TrackLevel